# Generated by Django 3.1.5 on 2021-01-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_defect_defectinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcinput',
            name='defect_type',
        ),
        migrations.AddField(
            model_name='qcinput',
            name='input_type',
            field=models.CharField(default='ftt', max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcinput',
            name='readcted',
            field=models.BooleanField(default=False),
        ),
    ]
