# Generated by Django 3.1.5 on 2021-01-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210127_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcinput',
            old_name='readcted',
            new_name='redacted',
        ),
    ]
