# Generated by Django 3.1.5 on 2021-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210127_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='qc_input',
            field=models.ManyToManyField(to='api.QcInput'),
        ),
        migrations.DeleteModel(
            name='DefectInput',
        ),
    ]
