# Generated by Django 3.1.5 on 2021-01-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210127_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcinput',
            name='redaction_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
