# Generated by Django 3.1.5 on 2021-01-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210130_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='sam',
            field=models.FloatField(default=3.4),
            preserve_default=False,
        ),
    ]
