# Generated by Django 3.1.5 on 2021-01-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_style_sam'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
