# Generated by Django 3.1.5 on 2021-02-21 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_productionorder_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedQcInput',
            fields=[
                ('qcinput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.qcinput')),
                ('deletion_datetime', models.DateTimeField(null=True)),
            ],
            bases=('api.qcinput',),
        ),
        migrations.RemoveField(
            model_name='qcinput',
            name='redacted',
        ),
        migrations.RemoveField(
            model_name='qcinput',
            name='redaction_datetime',
        ),
    ]
