# Generated by Django 3.1.5 on 2021-02-21 23:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210222_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedQcInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ftt', models.BooleanField(default=True)),
                ('input_type', models.CharField(choices=[('ftt', 'ftt'), ('rejected', 'rejected'), ('rectified', 'rectified'), ('defective', 'defective')], max_length=56)),
                ('size', models.CharField(max_length=16)),
                ('quantity', models.IntegerField(default=1)),
                ('deletion_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('defects', models.ManyToManyField(to='api.Defect')),
                ('production_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productionsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
