# Generated by Django 3.1.5 on 2021-04-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
