# Generated by Django 3.1.5 on 2021-01-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0004_auto_20210126_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=256)),
                ('defect', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DefectInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mes.defect')),
                ('qcInput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mes.qcinput')),
            ],
        ),
    ]
