# Generated by Django 3.1.5 on 2021-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0009_auto_20210127_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='qc_input',
        ),
        migrations.AddField(
            model_name='qcinput',
            name='defects',
            field=models.ManyToManyField(to='mes.Defect'),
        ),
    ]
