# Generated by Django 3.1.5 on 2021-01-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0011_qcinput_redaction_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={'ordering': ['operation']},
        ),
        migrations.AddField(
            model_name='qcinput',
            name='ftt',
            field=models.BooleanField(default=True),
        ),
    ]
