# Generated by Django 3.1.5 on 2021-02-21 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0016_auto_20210222_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcinput',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qcinput',
            name='input_type',
            field=models.CharField(choices=[('ftt', 'ftt'), ('rejected', 'rejected'), ('rectified', 'rectified'), ('defective', 'defective')], max_length=56),
        ),
        migrations.AlterField(
            model_name='qcinput',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='DeletedQcInput',
        ),
    ]
