# Generated by Django 3.1.5 on 2021-02-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0018_deletedqcinput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletedqcinput',
            options={'permissions': [('can_receive_new_qc_input_notification', 'Can receive notifications for new QC inputs')]},
        ),
        migrations.AlterModelOptions(
            name='qcinput',
            options={'permissions': [('can_receive_new_qc_input_notification', 'Can receive notifications for new QC inputs')]},
        ),
    ]
