# Generated by Django 3.1.5 on 2021-02-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0021_auto_20210224_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='sizes',
        ),
        migrations.CreateModel(
            name='SizeQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=256)),
                ('quantity', models.IntegerField()),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mes.style')),
            ],
        ),
    ]
