# Generated by Django 3.1.5 on 2021-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0022_auto_20210225_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='defects',
            field=models.ManyToManyField(to='mes.Defect'),
        ),
    ]
