# Generated by Django 3.1.5 on 2021-02-25 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0023_style_defects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedqcinput',
            name='size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='mes.sizequantity'),
        ),
        migrations.AlterField(
            model_name='qcinput',
            name='size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='mes.sizequantity'),
        ),
    ]
