# Generated by Django 3.1.5 on 2021-02-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0024_auto_20210225_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedqcinput',
            name='defects',
            field=models.ManyToManyField(blank=True, to='mes.Defect'),
        ),
        migrations.AlterField(
            model_name='qcinput',
            name='defects',
            field=models.ManyToManyField(blank=True, to='mes.Defect'),
        ),
    ]
