# Generated by Django 3.1.5 on 2021-02-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0025_auto_20210225_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedqcinput',
            name='input_type',
            field=models.CharField(choices=[('ftt', 'pass'), ('rejected', 'alter'), ('rectified', 'rectified'), ('defective', 'defective')], max_length=56),
        ),
        migrations.AlterField(
            model_name='deletedqcinput',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mes.sizequantity'),
        ),
        migrations.AlterField(
            model_name='qcinput',
            name='input_type',
            field=models.CharField(choices=[('ftt', 'pass'), ('rejected', 'alter'), ('rectified', 'rectified'), ('defective', 'defective')], max_length=56),
        ),
        migrations.AlterField(
            model_name='qcinput',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mes.sizequantity'),
        ),
    ]
