# Generated by Django 3.1.5 on 2021-02-25 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0026_auto_20210226_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='productionsession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='productionsession',
            name='line_number',
        ),
        migrations.AddField(
            model_name='productionsession',
            name='line',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='mes.line'),
            preserve_default=False,
        ),
    ]
