# Generated by Django 3.1.5 on 2021-02-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0027_auto_20210226_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsession',
            name='line',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mes.line'),
        ),
    ]
