# Generated by Django 3.1.5 on 2021-02-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0028_auto_20210226_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='quantity',
        ),
    ]
