# Generated by Django 3.1.5 on 2021-02-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0031_auto_20210226_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='operation',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
