# Generated by Django 3.1.5 on 2021-02-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0032_auto_20210226_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={},
        ),
    ]
