# Generated by Django 3.1.5 on 2021-02-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0033_auto_20210227_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedqcinput',
            old_name='ftt',
            new_name='is_ftt',
        ),
        migrations.RenameField(
            model_name='qcinput',
            old_name='ftt',
            new_name='is_ftt',
        ),
    ]
