# Generated by Django 3.1.5 on 2021-02-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0034_auto_20210228_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='number',
            field=models.IntegerField(),
        ),
    ]
