# Generated by Django 3.1.5 on 2021-02-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0037_auto_20210228_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineNumber',
            new_name='LineLocation',
        ),
    ]
