# Generated by Django 3.1.5 on 2021-02-28 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0040_auto_20210301_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.stylecategory'),
        ),
    ]
