# Generated by Django 3.1.5 on 2021-02-28 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0041_style_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='due_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productionsession',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
