# Generated by Django 3.1.5 on 2021-02-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0042_auto_20210301_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylecategory',
            options={'verbose_name': 'Style Category', 'verbose_name_plural': 'Style Categories'},
        ),
    ]
