# Generated by Django 3.1.5 on 2021-02-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0047_auto_20210301_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='style_category',
        ),
        migrations.AddField(
            model_name='stylecategory',
            name='defects',
            field=models.ManyToManyField(to='mes.Defect'),
        ),
    ]
