# Generated by Django 3.1.5 on 2021-02-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0048_auto_20210301_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylecategory',
            name='defects',
            field=models.ManyToManyField(blank=True, to='mes.Defect'),
        ),
    ]
