# Generated by Django 3.1.5 on 2021-03-01 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0049_auto_20210301_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='sam',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001, message='sam should be greater than 0')]),
        ),
    ]
