# Generated by Django 3.1.5 on 2021-03-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0053_auto_20210303_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='operation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mes.linelocation'),
        ),
        migrations.AlterField(
            model_name='productionsession',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mes.line'),
        ),
    ]
