# Generated by Django 3.1.5 on 2021-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0054_auto_20210303_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='operation',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
