# Generated by Django 3.1.5 on 2021-03-04 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0055_auto_20210304_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedqcinput',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qcinput',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
    ]
