# Generated by Django 3.1.5 on 2021-03-07 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0057_auto_20210305_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='order_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
        ),
    ]
