# Generated by Django 3.1.5 on 2021-03-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0058_productionorder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='order_number',
            field=models.CharField(max_length=256),
        ),
    ]
