# Generated by Django 3.1.5 on 2021-03-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mes', '0059_auto_20210309_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcAppState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('persisted_inputs_count', models.PositiveIntegerField()),
                ('synced_inputs_count', models.PositiveIntegerField()),
                ('production_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mes.productionsession')),
                ('signed_in_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
