# Generated by Django 3.1.5 on 2021-03-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0060_qcappstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcappstate',
            name='inputs_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
