# Generated by Django 3.1.5 on 2021-03-22 06:53

from django.db import migrations, models
import mes.models.prod_session


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0062_auto_20210320_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsessionbreak',
            name='end_time',
            field=models.TimeField(default=mes.models.prod_session.get_current_local_time),
        ),
        migrations.AlterField(
            model_name='productionsessionbreak',
            name='start_time',
            field=models.TimeField(default=mes.models.prod_session.get_current_local_time),
        ),
    ]
