# Generated by Django 3.1.5 on 2021-03-24 20:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0063_auto_20210322_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='order_number',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='defects',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to='mes.Defect'),
        ),
        migrations.AlterField(
            model_name='style',
            name='number',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
