# Generated by Django 3.1.5 on 2021-03-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0064_auto_20210325_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='defects',
            field=models.ManyToManyField(to='mes.Defect'),
        ),
        migrations.AddConstraint(
            model_name='productionsessionbreak',
            constraint=models.UniqueConstraint(fields=('start_time', 'end_time'), name='unique_break_timing'),
        ),
    ]
