# Generated by Django 3.1.5 on 2021-03-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0065_auto_20210325_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylecategory',
            name='defects',
        ),
    ]
