# Generated by Django 3.1.5 on 2021-03-26 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0066_remove_stylecategory_defects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='defect',
            name='operation',
        ),
        migrations.CreateModel(
            name='OperationDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mes.defect')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mes.operation')),
            ],
        ),
        migrations.AddField(
            model_name='deletedqcinput',
            name='operation_defects',
            field=models.ManyToManyField(blank=True, to='mes.OperationDefect'),
        ),
        migrations.AddField(
            model_name='qcinput',
            name='operation_defects',
            field=models.ManyToManyField(blank=True, to='mes.OperationDefect'),
        ),
        migrations.AddConstraint(
            model_name='operationdefect',
            constraint=models.UniqueConstraint(fields=('operation', 'defect'), name='unique_operation_defect'),
        ),
    ]
