# Generated by Django 3.1.5 on 2021-03-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0067_auto_20210326_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdefect',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mes.operation'),
        ),
    ]
