# Generated by Django 3.1.5 on 2021-03-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0069_auto_20210326_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='operation',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
