# Generated by Django 3.1.5 on 2021-03-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0070_defect_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='defect',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
