# Generated by Django 3.1.5 on 2021-03-29 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mes', '0072_auto_20210327_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcappstate',
            name='production_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mes.productionsession'),
        ),
        migrations.AlterField(
            model_name='qcappstate',
            name='signed_in_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
